FROM maven:3.6.3-openjdk-11

RUN apt-get update; apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs \
    && curl -L https://www.npmjs.com/install.sh | sh
RUN npm install -g nodemon

WORKDIR /opt/app

CMD ["./startDev.sh"]
